//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QReduction.Api {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QReduction.Api.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to this procedure.
        /// </summary>
        public static string Access_Unauthorized {
            get {
                return ResourceManager.GetString("Access_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Activation Code.
        /// </summary>
        public static string AccountActivationCode {
            get {
                return ResourceManager.GetString("AccountActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Already assigned to User in this Window.
        /// </summary>
        public static string AlreadyAssignedToUser {
            get {
                return ResourceManager.GetString("AlreadyAssignedToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant Not Delete  This Rang.
        /// </summary>
        public static string CanNotDeleteMulti {
            get {
                return ResourceManager.GetString("CanNotDeleteMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Not Restor This Rang.
        /// </summary>
        public static string CanNotRestorMulti {
            get {
                return ResourceManager.GetString("CanNotRestorMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant open new shift as there is an open one in this branch.
        /// </summary>
        public static string CantOpenShiftWhileOpendOne {
            get {
                return ResourceManager.GetString("CantOpenShiftWhileOpendOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This record cannot be deleted because it is related to other records.
        /// </summary>
        public static string Delete_RelatedDelete {
            get {
                return ResourceManager.GetString("Delete_RelatedDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Exist.
        /// </summary>
        public static string Exist_Code {
            get {
                return ResourceManager.GetString("Exist_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name Exist.
        /// </summary>
        public static string Exist_NameAr {
            get {
                return ResourceManager.GetString("Exist_NameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name Exist.
        /// </summary>
        public static string Exist_NameEn {
            get {
                return ResourceManager.GetString("Exist_NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exist Email.
        /// </summary>
        public static string Exists_Email {
            get {
                return ResourceManager.GetString("Exists_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or phone number already exists in the database.
        /// </summary>
        public static string Exists_EmailOrPhone {
            get {
                return ResourceManager.GetString("Exists_EmailOrPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exist Phone.
        /// </summary>
        public static string Exists_Phone {
            get {
                return ResourceManager.GetString("Exists_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exist UserName.
        /// </summary>
        public static string Exists_UserName {
            get {
                return ResourceManager.GetString("Exists_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Wil lBe Sent Soon.
        /// </summary>
        public static string FileWillBeSentSoon {
            get {
                return ResourceManager.GetString("FileWillBeSentSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Queue Id.
        /// </summary>
        public static string InvalidQueueId {
            get {
                return ResourceManager.GetString("InvalidQueueId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidresetPasswordCode.
        /// </summary>
        public static string InvalidresetPasswordCode {
            get {
                return ResourceManager.GetString("InvalidresetPasswordCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Shif Id.
        /// </summary>
        public static string InvalidShiftId {
            get {
                return ResourceManager.GetString("InvalidShiftId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string LangKey {
            get {
                return ResourceManager.GetString("LangKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username or Password.
        /// </summary>
        public static string Login_Invalid {
            get {
                return ResourceManager.GetString("Login_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password And New ConfirmationPassword dose not Matches.
        /// </summary>
        public static string NewPasswordError {
            get {
                return ResourceManager.GetString("NewPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Order Found For This User.
        /// </summary>
        public static string NoOrderFoundForThisUser {
            get {
                return ResourceManager.GetString("NoOrderFoundForThisUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Shift Opening In This Branch.
        /// </summary>
        public static string NoShiftOpenInThisBranch {
            get {
                return ResourceManager.GetString("NoShiftOpenInThisBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there is no user assigned to this shift.
        /// </summary>
        public static string NotAssignedUserInShift {
            get {
                return ResourceManager.GetString("NotAssignedUserInShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        public static string OldPasswordError {
            get {
                return ResourceManager.GetString("OldPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order is not available.
        /// </summary>
        public static string OrderIsNotAvailable {
            get {
                return ResourceManager.GetString("OrderIsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderNotFound.
        /// </summary>
        public static string OrderNotFound {
            get {
                return ResourceManager.GetString("OrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Required.
        /// </summary>
        public static string PhoneNumberRequired {
            get {
                return ResourceManager.GetString("PhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Already Added to Branch.
        /// </summary>
        public static string ServiceAlreadyAddedtoBranch {
            get {
                return ResourceManager.GetString("ServiceAlreadyAddedtoBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift is closed.
        /// </summary>
        public static string ShiftIsClosed {
            get {
                return ResourceManager.GetString("ShiftIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Settings Can not Be Null.
        /// </summary>
        public static string SystemSettingsCannotBeNull {
            get {
                return ResourceManager.GetString("SystemSettingsCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There Users Not Found.
        /// </summary>
        public static string ThereUsersNotFound {
            get {
                return ResourceManager.GetString("ThereUsersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserNotFound.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Code Not Match.
        /// </summary>
        public static string YourCodeNotMatch {
            get {
                return ResourceManager.GetString("YourCodeNotMatch", resourceCulture);
            }
        }
    }
}
